
# Reference: https://software.intel.com/en-us/articles/c0x-features-supported-by-intel-c-compiler/

set(_cmake_oldestSupported "(__INTEL_COMPILER >= 1400)")

set(Intel14_CXX11 "${_cmake_oldestSupported} && __cplusplus >= 201103L")
set(_cmake_feature_test_cxx_static_assert "${Intel14_CXX11}")
set(_cmake_feature_test_cxx_right_angle_brackets "${Intel14_CXX11}")
set(_cmake_feature_test_cxx_extended_friend_declarations "${Intel14_CXX11}")
set(_cmake_feature_test_cxx_auto_type "${Intel14_CXX11}")
set(_cmake_feature_test_cxx_delegating_constructors "${Intel14_CXX11}")
set(_cmake_feature_test_cxx_extern_templates "${Intel14_CXX11}")
set(_cmake_feature_test_cxx_rvalue_references "${Intel14_CXX11}")
set(_cmake_feature_test_cxx_constexpr "${Intel14_CXX11}")
set(_cmake_feature_test_cxx_variadic_templates "${Intel14_CXX11}")
set(_cmake_feature_test_cxx_alias_templates "${Intel14_CXX11}")
set(_cmake_feature_test_cxx_decltype "${Intel14_CXX11}")
set(_cmake_feature_test_cxx_defaulted_functions "${Intel14_CXX11}")
set(_cmake_feature_test_cxx_deleted_functions "${Intel14_CXX11}")
set(_cmake_feature_test_cxx_strong_enums "${Intel14_CXX11}")
set(_cmake_feature_test_cxx_nullptr "${Intel14_CXX11}")
set(_cmake_feature_test_cxx_explicit_conversions "${Intel14_CXX11}")
set(_cmake_feature_test_cxx_reference_qualified_functions "${Intel14_CXX11}")
set(_cmake_feature_test_cxx_raw_string_literals "${Intel14_CXX11}")
set(_cmake_feature_test_cxx_inline_namespaces "${Intel14_CXX11}")
set(_cmake_feature_test_cxx_inheriting_constructors "${Intel14_CXX11}")
set(_cmake_feature_test_cxx_trailing_return_types "${Intel14_CXX11}")
set(_cmake_feature_test_cxx_unrestricted_unions "${Intel14_CXX11}")
set(_cmake_feature_test_cxx_lambdas "${Intel14_CXX11}")
set(_cmake_feature_test_cxx_local_type_template_args "${Intel14_CXX11}")
set(_cmake_feature_test_cxx_generalized_initializers "${Intel14_CXX11}")
set(_cmake_feature_test_cxx_nonstatic_member_init "${Intel14_CXX11}")
set(_cmake_feature_test_cxx_attributes "${Intel14_CXX11}")
set(_cmake_feature_test_cxx_enum_forward_declarations "${Intel14_CXX11}")
set(_cmake_feature_test_cxx_final "${Intel14_CXX11}")
set(_cmake_feature_test_cxx_override "${Intel14_CXX11}")
set(_cmake_feature_test_cxx_range_for "${Intel14_CXX11}")
set(_cmake_feature_test_cxx_noexcept "${Intel14_CXX11}")
set(_cmake_feature_test_cxx_defaulted_move_initializers "${Intel14_CXX11}")
set(_cmake_feature_test_cxx_default_function_template_args "${Intel14_CXX11}")
set(_cmake_feature_test_cxx_long_long_type "${Intel14_CXX11}")
set(_cmake_feature_test_cxx_func_identifier "${Intel14_CXX11}")
set(_cmake_feature_test_cxx_variadic_macros "${Intel14_CXX11}")
set(_cmake_feature_test_cxx_template_template_parameters "${Intel14_CXX11}")


# Unknown or unsupported
# set(_cmake_feature_test_cxx_decltype_incomplete_return_types "${Intel14_CXX11}")
# set(_cmake_feature_test_cxx_alignas "${Intel14_CXX11}")
# set(_cmake_feature_test_cxx_alignof "${Intel14_CXX11}")
# set(_cmake_feature_test_cxx_thread_local "${Intel14_CXX11}")
# set(_cmake_feature_test_cxx_user_literals "${Intel14_CXX11}")
# set(_cmake_feature_test_cxx_sizeof_member "${Intel14_CXX11}")
# set(_cmake_feature_test_cxx_unicode_literals "${Intel14_CXX11}")
# set(_cmake_feature_test_cxx_uniform_initialization "${Intel14_CXX11}")
